### ISSUE TITLE
Data Doesn't Persist between Sessions

### ISSUE THREAD

**Issue by a-abraham** [ineptech/mirror#2]
The app is crashing a lot, and every single time I've been having to type in the URL for the transit, and retype out a regex. I will then hit 'save' at the bottom. Then occasionally the app will crash.

However changes don't seem to persist if the app crashes.

**Comment by ineptech** [comment]
You saw that there's a "Test" button to test the transit url/regex without saving?  Does it work?  Can you send me the url/regex you're using?

**Comment by a-abraham** [comment]
Yes I've been using the Test button to play around. Initially I was using only the test button. But when I encountered crashes, I decided to try saving the data.
(It's entirely possible it's just because of the crappy tablet i'm using)

URL: http://svc.metrotransit.org/NexTrip/56041

According to http://svc.metrotransit.org/   it is returning XML. So I tried creating a regex to parse the XML...

**Comment by ineptech** [comment]
I think I see the problem.  The app expects epoch time (e.g. # of seconds or miliseconds since 1/1/1970) and that service is sending a normal time (e.g. 2016-02-03T15:54:00).  

Two things I'll do later this evening:
1) Set it to try that time format
2) Set it to, if it can't parse the time format, just display whatever it finds instead of bombing out

To help, could you clarify which parameter you are trying to grab?  DepartureTime, DepartureText, soething else?

PS Thanks for the feedback!

**Comment by a-abraham** [comment]
I would be trying to grab whatever comes after <DepartureTime>2016-02-03T15:03:00
In this case, specifically 15:03

Also, thank you for getting back to me so quickly! Great job overall with the app, I quite like it since it adds the Bus route info!

**Comment by ineptech** [comment]
OK, will work on it this evening.  Also, could you clarify what wasn't being saved?  (There is already a bug about saving Latitude on the Weather module, that will be fixed shortly.  AFAIK everything else works.)

**Comment by a-abraham** [comment]
1) The Name of the Route (Default: Train work)
2) URL for Arrival Time
3) Regex

**Comment by ineptech** [comment]
Those work for me.  Sure you're hitting the "+" button to add the transit item?

**Comment by a-abraham** [comment]
My mistake. I interpreted that button as a way to add **Additional** transit items if I desired. I didn't realize there was an existing one above. 
Thanks for clarifying

**Comment by ineptech** [comment]
This is fixed and checked in; next push to Play store coming soon.
