### ISSUE TITLE
forecast.io changed domain name

### ISSUE THREAD

**Issue by nchuecos** [ineptech/mirror#20]
No weather info shows up on the app, maybe because of the change in domain name?
API still available on https://darksky.net/dev/, with key provided and free setup.

**Comment by ineptech** [comment]
Pushed a change to address this, will update the app in the play store tonight after the kids are in bed (hopefully, otherwise in the next day or two).  I believe your old api key (from forecast.io) will still work, but I made a new one just ot be safe.
